<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>uk.gov.moj.cpp.common</groupId>
        <artifactId>service-parent-pom</artifactId>
        <version>17.21.1</version>
    </parent>

    <groupId>uk.gov.moj.cpp.courtscheduler</groupId>
    <artifactId>courtscheduler-parent</artifactId>
    <version>17.0.2-CSP1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>CourtScheduler Service - Parent Module</name>

    <properties>
        <sonar.jacoco.itReportPath>${project.basedir}/../target/jacoco-it.exec
        </sonar.jacoco.itReportPath>
        <sonar.report.export.path>sonar-report.json</sonar.report.export.path>
        <sonar.scm.provider>git</sonar.scm.provider>
        <mvn.site.url>file://${project.build.directory}/site</mvn.site.url>
        <gihub.benas.random-beans.version>3.7.0</gihub.benas.random-beans.version>
        <cglib.version>3.3.0</cglib.version>
        <org.mockito.mockito-core.version>2.24.0</org.mockito.mockito-core.version>
        <junit-dataprovider.version>1.13.1</junit-dataprovider.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- junit-dataprovider should come from test utils once moved -->
            <dependency>
                <groupId>com.tngtech.java</groupId>
                <artifactId>junit-dataprovider</artifactId>
                <version>${junit-dataprovider.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>courtscheduler-api</module>
        <module>courtscheduler-integration-test</module>
        <module>courtscheduler-viewstore</module>
        <module>courtscheduler-service</module>
        <module>courtscheduler-healthchecks</module>

    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>external.atlassian.jgitflow</groupId>
                <artifactId>jgitflow-maven-plugin</artifactId>
                <configuration>
                    <flowInitContext>
                        <masterBranchName>dev/release</masterBranchName>
                        <developBranchName>master</developBranchName>
                        <featureBranchPrefix>dev/feature-</featureBranchPrefix>
                        <releaseBranchPrefix>dev/release-</releaseBranchPrefix>
                        <hotfixBranchPrefix>dev/hotfix-</hotfixBranchPrefix>
                        <versionTagPrefix>v</versionTagPrefix>
                    </flowInitContext>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <enableSshAgent>true</enableSshAgent>
                    <pushReleases>true</pushReleases>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
