#ARG base_image=crmdvrepo01.azurecr.io/wildfly:310122
ARG baseImageTag
FROM crmdvrepo01.azurecr.io/hmcts/wildfly:${baseImageTag}
ARG version
ARG repo_loc=https://libraries-internal.mdv.cpp.nonlive/artifactory/repocentral
ARG wildfly_home=/opt/jboss/wildfly
ARG wildfly_user=jboss
ARG context_group_name=courtscheduler
ARG context_name=listing-courtscheduler

# service war file
ADD ${repo_loc}/uk/gov/moj/cpp/${context_group_name}/${context_name}-api/${version}/${context_name}-api-${version}.war ${wildfly_home}/standalone/deployments/
USER root
RUN chown ${wildfly_user}:${wildfly_user} ${wildfly_home}/standalone/deployments/${context_name}-api-${version}.war

# liquibase jars & config
RUN mkdir /tmp/liquibase
ADD ${repo_loc}/uk/gov/moj/cpp/${context_group_name}/${context_name}-viewstore-liquibase/${version}/${context_name}-viewstore-liquibase-${version}.jar /tmp/liquibase/${context_name}-viewstore-liquibase.jar
RUN chmod -R 755 /tmp/liquibase
COPY scripts/liquibase.sh /tmp/liquibase/liquibase.sh
RUN chown ${wildfly_user}:${wildfly_user} /tmp/liquibase/liquibase.sh && chmod 755 /tmp/liquibase/liquibase.sh
RUN mkdir /opt/cpp-tools
USER ${wildfly_user}
LABEL base_image {baseImageTag}