package uk.gov.moj.cpp.courtscheduler.repository;

import static uk.gov.moj.cpp.courtscheduler.domain.RequestParameterConstant.EXACT_HEARING_START_DATETIME;

import uk.gov.moj.cpp.courtscheduler.domain.AllocatedListingEachBooked;
import uk.gov.moj.cpp.courtscheduler.domain.AllocatedListingTotalBooked;
import uk.gov.moj.cpp.courtscheduler.domain.HearingSlotRequestParam;
import uk.gov.moj.cpp.courtscheduler.domain.IdResponse;
import uk.gov.moj.cpp.courtscheduler.domain.MiFilterCriteria;
import uk.gov.moj.cpp.courtscheduler.domain.utils.DateUtils;
import uk.gov.moj.cpp.courtscheduler.persist.entity.AllocatedListing;

import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Date;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.TemporalType;

import org.apache.commons.lang3.tuple.Pair;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Migrated 1:1 from the legacy DeltaSpike {@code AbstractFullEntityRepository<AllocatedListing, String>}.
 *
 * <p>Method-name derived queries ({@code findByHearingId}, {@code findByCourtScheduleId}…) are
 * generated by Spring Data exactly as DeltaSpike used to generate them. JPQL- or native-SQL-only
 * queries use the {@link Query} annotation. Methods that need an explicit {@code EntityManager}
 * (dynamic SQL builders, raw native row → record mapping, post-processing into MI domain types)
 * live in the package-private {@link AllocatedListingRepositoryCustom} fragment + its
 * {@code …Impl} class — both colocated in this file so a single read shows the whole repository.</p>
 */
@Repository
public interface AllocatedListingRepository
        extends JpaRepository<AllocatedListing, String>, AllocatedListingRepositoryCustom {

    /** Spring Data generates the JPQL: {@code SELECT al FROM AllocatedListing al WHERE al.hearingId = :hearingId}. */
    List<AllocatedListing> findByHearingId(String hearingId);

    /** Spring Data generates the JPQL: {@code SELECT al FROM AllocatedListing al WHERE al.courtScheduleId = :courtScheduleId}. */
    List<AllocatedListing> findByCourtScheduleId(String courtScheduleId);

    /** Spring Data generates the JPQL combining both equals filters. */
    List<AllocatedListing> findByCourtScheduleIdAndHearingId(String courtScheduleId, String hearingId);

    /** Spring Data generates the JPQL: {@code WHERE al.updatedOn > :fromDate AND al.updatedOn < :toDate}. */
    List<AllocatedListing> findByUpdatedOnGreaterThanAndUpdatedOnLessThan(Date fromDate, Date toDate);

    @Query("""
            SELECT COALESCE(SUM(al.duration), 0)
              FROM AllocatedListing al
             WHERE al.courtScheduleId = :courtScheduleId
            """)
    Integer findTotalAllocatedDurationByCourtScheduleId(@Param("courtScheduleId") String courtScheduleId);

    @Query("""
            SELECT new uk.gov.moj.cpp.courtscheduler.domain.AllocatedListingEachBooked(
                       al.courtScheduleId, al.duration, al.hearingStartTime)
              FROM AllocatedListing al
             WHERE al.courtScheduleId IN :courtScheduleIds
            """)
    List<AllocatedListingEachBooked> getAllocatedListingsEachBookedByCourtScheduleId(
            @Param("courtScheduleIds") List<String> courtScheduleIds);

    @Modifying
    @Transactional
    @Query(value = """
            DELETE FROM allocated_listings
             WHERE court_schedule_id IN (
                   SELECT cs.id FROM court_schedule cs
                    WHERE cs.session_start < (CURRENT_DATE - :numberOfDays))
            """, nativeQuery = true)
    int deleteRedundantRotaData(@Param("numberOfDays") int numberOfDays);

    // ---------------------------------------------------------------------
    //  Backwards-compatible aliases for methods that DeltaSpike's @EntityRepository
    //  auto-generated and that call sites in tests still use. JpaRepository already
    //  provides {@code save}, {@code saveAndFlush}, {@code findById}, {@code findAll},
    //  {@code delete} — these defaults preserve the legacy method names.
    // ---------------------------------------------------------------------

    default AllocatedListing findBy(final String id) {
        return findById(id).orElse(null);
    }

    default void remove(final AllocatedListing allocatedListing) {
        delete(allocatedListing);
    }

    default AllocatedListing merge(final AllocatedListing allocatedListing) {
        return save(allocatedListing);
    }
}

/**
 * Spring Data {@code Custom} fragment for {@link AllocatedListingRepository}.
 *
 * <p>Holds the methods that can't be expressed as a method-name derived query or a
 * single {@code @Query}: ones that build a result type from raw native rows, post-process
 * results into a different domain type, or rely on the {@link AllocatedHearingsQueryBuilder}
 * to assemble dynamic SQL. Spring Data auto-wires this fragment into the main
 * repository interface via the {@code …Impl} naming convention.</p>
 */
interface AllocatedListingRepositoryCustom {

    /**
     * Native {@code GROUP BY} on {@code allocated_listings} joined with {@code court_schedule}
     * to produce a per-{@code courtScheduleId} total — count of listings for slot-based
     * schedules, sum of durations otherwise. Result rows are unpacked into the
     * {@link AllocatedListingTotalBooked} record.
     */
    List<AllocatedListingTotalBooked> getAllocatedListingsByCourtScheduleId(List<String> courtScheduleIds);

    /**
     * Calls {@link AllocatedListingRepository#findByUpdatedOnGreaterThanAndUpdatedOnLessThan(java.util.Date, java.util.Date)}
     * and projects the result into the MI domain type.
     */
    List<uk.gov.moj.cpp.courtscheduler.domain.mi.AllocatedListing> findByUpdatedOnGreaterThanAndUpdatedOnLessThan(MiFilterCriteria miFilterCriteria);

    /**
     * Dynamic SQL produced by {@link AllocatedHearingsQueryBuilder}; returns a paged
     * set of hearing-id rows plus the total row count.
     */
    Pair<Integer, Set<IdResponse>> findHearingIdsBy(HearingSlotRequestParam hearingIdsReq);
}

/**
 * Spring Data picks this up by the {@code …Impl} naming convention as the implementation
 * of {@link AllocatedListingRepositoryCustom} — see Spring Data Reference §4.6.
 */
class AllocatedListingRepositoryImpl implements AllocatedListingRepositoryCustom {

    @PersistenceContext
    private EntityManager entityManager;

    @Override
    public List<AllocatedListingTotalBooked> getAllocatedListingsByCourtScheduleId(final List<String> courtScheduleIds) {
        final String sql = """
            SELECT al.court_schedule_id,
                   CASE
                       WHEN cs.is_slot_based = true THEN CAST(COUNT(*) AS BIGINT)
                       ELSE CAST(SUM(al.duration) AS BIGINT)
                   END AS total_booked
            FROM allocated_listings al
            JOIN court_schedule cs ON al.court_schedule_id = cs.id
            WHERE al.court_schedule_id IN :csIds
            GROUP BY al.court_schedule_id, cs.is_slot_based
            """;

        @SuppressWarnings("unchecked")
        final List<Object[]> results = entityManager.createNativeQuery(sql)
                .setParameter("csIds", courtScheduleIds)
                .getResultList();

        return results.stream()
                .map(row -> new AllocatedListingTotalBooked((String) row[0], ((Number) row[1]).longValue()))
                .toList();
    }

    @Override
    public List<uk.gov.moj.cpp.courtscheduler.domain.mi.AllocatedListing> findByUpdatedOnGreaterThanAndUpdatedOnLessThan(
            final MiFilterCriteria miFilterCriteria) {

        // Re-uses the method-name query Spring Data generates on the main interface, via
        // a lookup so this Custom impl doesn't require the main interface bean.
        final List<AllocatedListing> allocatedListings = entityManager.createQuery(
                        "SELECT al FROM AllocatedListing al "
                                + "WHERE al.updatedOn > :fromDate AND al.updatedOn < :toDate",
                        AllocatedListing.class)
                .setParameter("fromDate", DateUtils.getDate(miFilterCriteria.getFromLocalDate()))
                .setParameter("toDate", DateUtils.getDate(miFilterCriteria.getToLocalDate()))
                .getResultList();

        return allocatedListings.stream().map(entity -> {
            final uk.gov.moj.cpp.courtscheduler.domain.mi.AllocatedListing mi =
                    new uk.gov.moj.cpp.courtscheduler.domain.mi.AllocatedListing();
            mi.setId(entity.getId());
            mi.setOucode(entity.getOucode());
            mi.setCourtRoomId(entity.getCourtRoomId());
            mi.setCreatedOn(entity.getCreatedOn());
            mi.setBookingId(entity.getBookingId());
            mi.setHearingId(entity.getHearingId());
            mi.setCourtScheduleId(entity.getCourtScheduleId());
            mi.setUpdatedOn(entity.getUpdatedOn());
            mi.setDuration(entity.getDuration());
            mi.setHearingStartTime(entity.getHearingStartTime());
            mi.setRotaBusinessType(entity.getRotaBusinessType());
            return mi;
        }).toList();
    }

    @Override
    public Pair<Integer, Set<IdResponse>> findHearingIdsBy(final HearingSlotRequestParam hearingIdsReq) {
        final AllocatedHearingsQueryBuilder allocatedHearingsQueryCtx = new AllocatedHearingsQueryBuilder(hearingIdsReq);
        final jakarta.persistence.Query pageQuery =
                entityManager.createNativeQuery(allocatedHearingsQueryCtx.getAllocatedHearingsQuery());
        allocatedHearingsQueryCtx.getPagedQueryParamMap().forEach((k, v) -> {
            if (EXACT_HEARING_START_DATETIME.getLabel().equals(k)) {
                final Instant instant = Instant.parse((String) v);
                pageQuery.setParameter(k, Timestamp.from(instant), TemporalType.TIMESTAMP);
            } else {
                pageQuery.setParameter(k, v);
            }
        });
        @SuppressWarnings("unchecked")
        final List<Object[]> resultList = pageQuery.getResultList();
        final Set<IdResponse> pageResultSet = resultList.stream()
                .map(AllocatedListingRepositoryImpl::toIdResponse)
                .collect(Collectors.toCollection(LinkedHashSet::new));
        final int totalCount = resultList.isEmpty() ? 0 : ((Number) resultList.get(0)[5]).intValue();

        return Pair.of(totalCount, pageResultSet);
    }

    private static IdResponse toIdResponse(final Object[] row) {
        return new IdResponse((String) row[0], (String) row[1], getLocalDate(row[2]), getLong(row[3]), getLong(row[4]));
    }

    private static Long getLong(final Object item) {
        return item == null ? null : ((Number) item).longValue();
    }

    private static LocalDate getLocalDate(final Object item) {
        if (item == null) {
            return null;
        }
        if (item instanceof LocalDate ld) {
            return ld;
        }
        if (item instanceof java.sql.Date sqlDate) {
            return sqlDate.toLocalDate();
        }
        if (item instanceof java.util.Date utilDate) {
            return new java.sql.Date(utilDate.getTime()).toLocalDate();
        }
        throw new IllegalArgumentException("Unsupported date shape from native query: " + item.getClass());
    }
}
