package uk.gov.moj.cpp.courtscheduler.repository;

import uk.gov.moj.cpp.courtscheduler.openapi.model.AllocatedListingEachBooked;
import uk.gov.moj.cpp.courtscheduler.domain.utils.DateUtils;
import uk.gov.moj.cpp.courtscheduler.persist.entity.AllocatedListing;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Migrated 1:1 from the legacy DeltaSpike {@code AbstractFullEntityRepository<AllocatedListing, String>}.
 *
 * <p>Method-name derived queries ({@code findByHearingId}, {@code findByCourtScheduleId}…) are
 * generated by Spring Data exactly as DeltaSpike used to generate them. JPQL- or native-SQL-only
 * queries use the {@link Query} annotation. Methods that need an explicit {@code EntityManager}
 * (dynamic SQL builders, raw native row → record mapping, post-processing into MI domain types)
 * live in the package-private {@link AllocatedListingRepositoryCustom} fragment + its
 * {@code …Impl} class — both colocated in this file so a single read shows the whole repository.</p>
 */
@Repository
public interface AllocatedListingRepository
        extends JpaRepository<AllocatedListing, String>, AllocatedListingRepositoryCustom {

    /** Spring Data generates the JPQL: {@code SELECT al FROM AllocatedListing al WHERE al.hearingId = :hearingId}. */
    List<AllocatedListing> findByHearingId(String hearingId);

    /**
     * Confirmed rows only, by construction. A reservation carries its bookingId in
     * {@code hearing_id} and leaves {@code booking_id} null (see
     * {@code ReservationService.toReservedSlot}); only the row written when a booking is
     * confirmed is stamped with {@code booking_id}. So a non-empty result here means the
     * booking was shared, with no {@code expires_at} filter needed to say so.
     */
    List<AllocatedListing> findByBookingId(String bookingId);

    /**
     * Every reservation whose hold has lapsed — {@code expires_at} set and before the given
     * cutoff. Returns rows rather than deleting them so the caller can perform the full
     * three-step release — a bare DELETE would strand the capacity on court_schedule.
     * Self-healing: not scoped to "yesterday", so a missed daily run's backlog is still swept.
     */
    @Query(value = """
            SELECT al.*
            FROM allocated_listings al
            WHERE al.expires_at IS NOT NULL
              AND al.expires_at < :cutoff
            """, nativeQuery = true)
    List<AllocatedListing> findExpiredReservedSessions(@Param("cutoff") LocalDate cutoff);

    /** Spring Data generates the JPQL: {@code SELECT al FROM AllocatedListing al WHERE al.courtScheduleId = :courtScheduleId}. */
    List<AllocatedListing> findByCourtScheduleId(String courtScheduleId);

    /** Spring Data generates the JPQL combining both equals filters. */
    List<AllocatedListing> findByCourtScheduleIdAndHearingId(String courtScheduleId, String hearingId);

    /** Spring Data generates the JPQL: {@code WHERE al.updatedOn > :fromDate AND al.updatedOn < :toDate}. */
    List<AllocatedListing> findByUpdatedOnGreaterThanAndUpdatedOnLessThan(Instant fromDate, Instant toDate);

    @Query("""
            SELECT COALESCE(SUM(al.duration), 0)
              FROM AllocatedListing al
             WHERE al.courtScheduleId = :courtScheduleId
            """)
    Integer findTotalAllocatedDurationByCourtScheduleId(@Param("courtScheduleId") String courtScheduleId);

    @Query("""
            SELECT al.courtScheduleId, al.duration, al.hearingStartTime
              FROM AllocatedListing al
             WHERE al.courtScheduleId IN :courtScheduleIds
            """)
    List<Object[]> findAllocatedListingsEachBookedRowsByCourtScheduleId(
            @Param("courtScheduleIds") List<String> courtScheduleIds);

    default List<AllocatedListingEachBooked> getAllocatedListingsEachBookedByCourtScheduleId(
            final List<String> courtScheduleIds) {
        return findAllocatedListingsEachBookedRowsByCourtScheduleId(courtScheduleIds).stream()
                .map(row -> new AllocatedListingEachBooked()
                        .courtScheduleId((String) row[0])
                        .duration((Integer) row[1])
                        .hearingStartTime(DateUtils.toOffsetDateTime((Instant) row[2])))
                .toList();
    }

    @Modifying
    @Transactional
    @Query(value = """
            DELETE FROM allocated_listings
             WHERE court_schedule_id IN (
                   SELECT cs.id FROM court_schedule cs
                    WHERE cs.session_start < (CURRENT_DATE - :numberOfDays))
            """, nativeQuery = true)
    int deleteRedundantRotaData(@Param("numberOfDays") int numberOfDays);

    /** Rows for a hearing ordered by the joined session's start — multiday callers rely on this ordering. */
    @Query(value = """
            SELECT al.*
            FROM allocated_listings al
            JOIN court_schedule cs ON cs.id = al.court_schedule_id
            WHERE al.hearing_id = :hearingId
            ORDER BY cs.session_start ASC
            """, nativeQuery = true)
    List<AllocatedListing> findByHearingIdOrderBySessionDateAsc(@Param("hearingId") String hearingId);

    /** Deletes a hearing's rows whose joined session starts after the cutoff (multiday shrink). Returns rows deleted. */
    @Modifying
    @Transactional
    @Query(value = """
            DELETE FROM allocated_listings al
             WHERE al.hearing_id = :hearingId
               AND al.court_schedule_id IN (
                   SELECT cs.id FROM court_schedule cs WHERE cs.session_start > :cutoff)
            """, nativeQuery = true)
    int deleteByHearingIdAndSessionDateGreaterThan(@Param("hearingId") String hearingId,
                                                   @Param("cutoff") LocalDate cutoff);

    /**
     * Force the source column on all allocated_listings rows for a given hearingId.
     * Used by the Crown fallback path — the saveBookedSlots pipeline doesn't reliably
     * propagate the caller-supplied source label in all branches. This method guarantees
     * per-caller observability (CROWN_FB_LIST/ADJOURN/UPDATE) on the DB row.
     */
    @Transactional
    default int updateSourceByHearingId(final String hearingId, final String source) {
        if (source == null || source.isBlank()) {
            return 0;
        }
        final List<AllocatedListing> rows = findByHearingId(hearingId);
        rows.forEach(row -> {
            row.setSource(source);
            save(row);
        });
        return rows.size();
    }

    // ---------------------------------------------------------------------
    //  Backwards-compatible aliases for methods that DeltaSpike's @EntityRepository
    //  auto-generated and that call sites in tests still use. JpaRepository already
    //  provides {@code save}, {@code saveAndFlush}, {@code findById}, {@code findAll},
    //  {@code delete} — these defaults preserve the legacy method names.
    // ---------------------------------------------------------------------

    default AllocatedListing findBy(final String id) {
        return findById(id).orElse(null);
    }

    default void remove(final AllocatedListing allocatedListing) {
        delete(allocatedListing);
    }

    default AllocatedListing merge(final AllocatedListing allocatedListing) {
        return save(allocatedListing);
    }
}
