justiceAreaId=rotaSchedule.rotaPeriod.justiceAreaId
justiceAreaType=rotaSchedule.rotaPeriod.justiceAreaType
rotaPeriodStartDate=rotaSchedule.rotaPeriod.startDate
rotaPeriodEndDate=rotaSchedule.rotaPeriod.endDate

#-- Magistates details --
magistrateTitle=rotaSchedule.magistrates.magistrate.title
magistrateSurname=rotaSchedule.magistrates.magistrate.surname
magistrateForenames=rotaSchedule.magistrates.magistrate.forenames
magistrateEmailAddress=rotaSchedule.magistrates.magistrate.emailAddress

#-- District Judge details --
judgeTitle=rotaSchedule.districtJudges.districtJudge.title
judgeSurname=rotaSchedule.districtJudges.districtJudge.surname
judgeForenames=rotaSchedule.districtJudges.districtJudge.forenames
judgeEmailAddress=rotaSchedule.districtJudges.districtJudge.emailAddress

#-- Venues
venue.venueId=rotaSchedule.venues.venue.venueId
venueName=rotaSchedule.venues.venue.name

#-- Locations
location.locationId=rotaSchedule.locations.location.locationId
location.name=rotaSchedule.locations.location.name

#-- Court Listing Profile --
sessionDate=rotaSchedule.courtListingProfiles.courtListingProfile.sessionDate
session=rotaSchedule.courtListingProfiles.courtListingProfile.session
panel=rotaSchedule.courtListingProfiles.courtListingProfile.panel
business=rotaSchedule.courtListingProfiles.courtListingProfile.business
venueId=rotaSchedule.courtListingProfiles.courtListingProfile.venueId
locationId=rotaSchedule.courtListingProfiles.courtListingProfile.locationId
welshSpeaking=rotaSchedule.courtListingProfiles.courtListingProfile.welshSpeaking

#-- Schedule Details --
slot=rotaSchedule.schedules.schedule.slot
isDoubleBooked=rotaSchedule.schedules.schedule.isDoubleBooked