package uk.gov.moj.cpp.courtscheduler.api.accesscontrol.drl;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.courtscheduler.api.accesscontrol.PermissionConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "API - Action - courtscheduler.create"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.create");
        eval(userAndGroupProvider.hasPermission($action, PermissionConstants.createCourtSchedulePermission()));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.validate.create"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.validate.create");
        eval(userAndGroupProvider.hasPermission($action, PermissionConstants.createCourtSchedulePermission()));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.update.court_schedule"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.update");
        eval(userAndGroupProvider.hasPermission($action, PermissionConstants.createCourtSchedulePermission()));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.validate.update"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.validate.update");
        eval(userAndGroupProvider.hasPermission($action, PermissionConstants.createCourtSchedulePermission()));
  then
    $outcome.setSuccess(true);
end


rule "API - Action - courtscheduler.delete"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.delete");
        eval(userAndGroupProvider.hasPermission($action, PermissionConstants.createCourtSchedulePermission()));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.get.court_schedule"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.get.court_schedule");
        eval(userAndGroupProvider.hasPermission($action, PermissionConstants.getCourtSchedulePermission()));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.validate.delete"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.validate.delete");
        eval(userAndGroupProvider.hasPermission($action, PermissionConstants.createCourtSchedulePermission()));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.update.hearing.slots"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.update.hearing.slots");
         eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.search.update.hearing.slots"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.search.update.hearing.slots");
         eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.get.hearing.slots"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.get.hearing.slots");
        eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.remove.hearing.slots"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.remove.hearing.slots");
        eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.get.hearing.ids"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.get.hearing.ids");
        eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.search.book.hearing.slots"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.search.book.hearing.slots");
      eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.list.hearings-in-court-sessions"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.list.hearings-in-court-sessions");
        eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.create.provisional.booking"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.create.provisional.booking");
        eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.get.provisional.booking"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.get.provisional.booking");
        eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.export.court_schedule"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.export.court_schedule");
         eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.export.court_schedule_judiciary"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.export.court_schedule_judiciary");
         eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.export.allocated_listings"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.export.allocated_listings");
         eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.oucode.migrate"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.oucode.migrate");
        eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.rotasl.process_rota_files"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.rotasl.process_rota_files");
        eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.rotasl.clean_redundant_rota_data"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.rotasl.clean_redundant_rota_data");
        eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - courtscheduler.search.court-schedules-by-id"
  when
    $outcome: Outcome();
    $action: Action(name == "courtscheduler.search.court-schedules-by-id");
        eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "API - Action - listingcourtscheduler.query.organisation-units-hmi-status"
  when
    $outcome: Outcome();
    $action: Action(name == "listingcourtscheduler.query.organisation-units-hmi-status");
        eval(true);
  then
    $outcome.setSuccess(true);
end

rule "API - Action - listingcourtscheduler.query.organisation-unit-hmi-status"
  when
    $outcome: Outcome();
    $action: Action(name == "listingcourtscheduler.query.organisation-unit-hmi-status");
        eval(true);
  then
    $outcome.setSuccess(true);
end
