<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>uk.gov.moj.cpp.courtscheduler</groupId>
        <artifactId>listingcourtscheduler-parent</artifactId>
        <version>17.0.50-CCT2343-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <artifactId>listingcourtscheduler-domain</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.databind.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons.lang3.version}</version>
        </dependency>


        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.framework-generators</groupId>
            <artifactId>rest-adapter-core</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.common.library.utils</groupId>
            <artifactId>cpp-platform-test-utils</artifactId>
            <version>${cpp-platform-test-utils.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
