#%RAML 0.8
title: Court Scheduler API
baseUri: http://localhost:8080/courtscheduler-api/rest/courtscheduler
mediaType: application/json
protocols: [ HTTP, HTTPS ]

/courtschedule:
  description: |
    Create Court Schedule
  post:
    description: |
      ...
      (mapping):
          requestType: application/vnd.courtscheduler.create+json
          name: courtscheduler.create
      ...
    body:
      application/vnd.courtscheduler.create+json:
        schema: !include json/schema/courtscheduler.create.json
        example: !include json/courtscheduler.create.json
    responses:
      202:
        description: OK

  get:
    description: |
      Query via parameters
      ...
      (mapping):
          responseType: application/vnd.courtscheduler.get+json
          name: courtscheduler.get.court_schedule
      ...
    queryParameters:
      courtCentreId:
        type: string
        required: true
      courtRoomId:
        type: string
        required: false
      businessType:
        type: string
        required: false
      sessionStartDate:
        type: string
        required: true
      sessionEndDate:
        type: string
        required: true
      pageSize:
        description: Number of records to be displayed per page
        type: string
        required: true
      pageNumber:
        description: currentPageNumber details
        type: string
        required: true
    responses:
      200:
        body:
          application/vnd.courtscheduler.get+json:
            schema: !include json/schema/courtscheduler.get.court_schedule.json
            example: !include json/courtscheduler.get.court_schedule.json

/courtschedule/edit:
  post:
    description: |
      ...
      (mapping):
          requestType: application/vnd.courtscheduler.update+json
          name: courtscheduler.update
      ...
    body:
      application/vnd.courtscheduler.update+json:
        schema: !include json/schema/courtscheduler.update.json
        example: !include json/courtscheduler.update.json
    responses:
      202:
        description: OK

/courtschedule/delete:
  post:
    description: |
      ...
      (mapping):
          requestType: application/vnd.courtscheduler.delete+json
          name: courtscheduler.delete
      ...
    body:
      application/vnd.courtscheduler.delete+json:
        schema: !include json/schema/courtscheduler.delete.json
        example: !include json/courtscheduler.delete.json
    responses:
      200:
        body:
          application/vnd.courtscheduler.delete.response+json:
            schema: !include json/schema/courtscheduler.delete.response.json
            example: !include json/courtscheduler.delete.response.json

/hearingslots/{hearingId}:
  delete:
    description:  |
      You can remove slots for the given hearing with hearingId through this DELETE request
      ...
      (mapping):
          requestType: application/vnd.courtscheduler.remove.hearing.slots+json
          name: courtscheduler.remove.hearing.slots
      ...
    body:
      application/vnd.courtscheduler.remove.hearing.slots+json:
    responses:
      202:
        description: Request Accepted

/hearingslots:
  put:
    description:  |
      You can allocate a hearing slot through this POST request
      ...
      (mapping):
          requestType: application/vnd.courtscheduler.update.hearing.slots+json
          name: courtscheduler.update.hearing.slots
      ...
    body:
      application/vnd.courtscheduler.update.hearing.slots+json:
        example:
          !include json/courtscheduler.update.hearing.slots.json
        schema:
          !include json/schema/courtscheduler.update.hearing.slots.json
    responses:
      204:
        description: No Content

  get:
    description: |
      Query via parameters
        ...
        (mapping):
            responseType: application/vnd.courtscheduler.get.hearing.slots+json
            name: courtscheduler.get.hearing.slots
        ...
    queryParameters:
      panel:
        description: panel Type ( ADULT/YOUTH/ADULT,YOUTH)
        type: string
        required: true
      sessionStartDate:
        description: startDate
        type: string
        required: true
      sessionEndDate:
        description: endDate
        type: string
        required: true
      oucodeL2Code:
        description: Operational unit
        type: string
        required: false
      ouCode:
        description: Courthouse oucode
        type: string
        required: false
      courtRoomId:
        description: courtRoomId
        type: string
        required: false
      courtRoomNumber:
        description: courtRoomNumber
        type: string
        required: false
      businessType:
        description: businessType
        type: string
        required: false
      courtSession:
        description: AM/PM/AD or comma separeted --> AM,PM,AD
        type: string
        required: false
      pageSize:
        description: Number of records to be displayed per page
        type: string
        required: true
      pageNumber:
        description: currentPageNumber details
        type: string
        required: true
    responses:
      200:
        body:
          application/vnd.courtscheduler.get.hearing.slots+json:
            example: !include json/courtscheduler.get.hearing.slots.json
            schema: !include json/schema/courtscheduler.get.hearing.slots.json

/provisionalBooking:
  post:
    description:  |
      You can book slot provisionally by giving corresponding courtScheduleId(s) inside request body
      ...
        (mapping):
            requestType: application/vnd.courtscheduler.create.provisional.booking+json
            name: courtscheduler.create.provisional.booking
      ...
    body:
      application/vnd.courtscheduler.create.provisional.booking+json:
        schema:  !include json/schema/courtscheduler.create.provisional.booking.json
        example:  !include json/courtscheduler.create.provisional.booking.json
    responses:
      200:
        body:
          example: !include json/courtscheduler.create.provisional.booking.response.json
          schema:  !include json/schema/courtscheduler.create.provisional.booking.response.json

  get:
    description:  |
      Query via parameters
      ...
        (mapping):
            responseType: application/vnd.courtscheduler.get.provisional.booking+json
            name: courtscheduler.get.provisional.booking
      ...
    queryParameters:
      bookingIds:
        description: booking ids as comma separated
        type: string
        required: true
    responses:
      200:
        body:
          application/vnd.courtscheduler.get.provisional.booking+json:
            example: !include json/courtscheduler.get.provisional.booking.json
            schema:  !include json/schema/courtscheduler.get.provisional.booking.json

/mi/court_schedules:
  get:
    description: |
      Query via parameters
        ...
        (mapping):
            responseType: application/vnd.courtscheduler.export.court_schedule+json
            name: courtscheduler.export.court_schedule
        ...
    queryParameters:
      fromDate:
        description: from date of the data range
        type: string
        required: true
      toDate:
        description: to date of the data range
        type: string
        required: true
    responses:
      200:
        body:
          application/vnd.courtscheduler.export.court_schedule+json:
            example: !include json/courtscheduler.export.court_schedule.json
            schema: !include json/schema/courtscheduler.export.court_schedule.json

/mi/court_schedule_judiciaries:
  get:
    description: |
      Query via parameters
        ...
        (mapping):
            responseType: application/vnd.courtscheduler.export.court_schedule_judiciary+json
            name: courtscheduler.export.court_schedule_judiciary
        ...
    queryParameters:
      fromDate:
        description: from date of the data range
        type: string
        required: true
      toDate:
        description: to date of the data range
        type: string
        required: true
    responses:
      200:
        body:
          application/vnd.courtscheduler.export.court_schedule_judiciary+json:
            example: !include json/courtscheduler.export.court_schedule_judiciary.json
            schema: !include json/schema/courtscheduler.export.court_schedule_judiciary.json

/mi/allocated_listings:
  get:
    description: |
      Query via parameters
        ...
        (mapping):
            responseType: application/vnd.courtscheduler.export.allocated_listings+json
            name: courtscheduler.export.allocated_listings
        ...
    queryParameters:
      fromDate:
        description: from date of the data range
        type: string
        required: true
      toDate:
        description: to date of the data range
        type: string
        required: true
    responses:
      200:
        body:
          application/vnd.courtscheduler.export.allocated_listings+json:
            example: !include json/courtscheduler.export.allocated_listings.json
            schema: !include json/schema/courtscheduler.export.allocated_listings.json

/oucode/migrate:
  post:
    description: |
      ...
      (mapping):
          requestType: application/vnd.courtscheduler.oucode.migrate+json
          name: courtscheduler.oucode.migrate
      ...
    body:
      application/vnd.courtscheduler.oucode.migrate+json:
        schema: !include json/schema/courtscheduler.oucode.migrate.json
        example: !include json/courtscheduler.oucode.migrate.json
    responses:
      202:
        description: OK

/rotasl/process-rota-files:
  post:
    description: |
      unprocessed rotasl files should be pulled from azure container and being processed into scsl database for the schedule of the ljas
        ...
        (mapping):
            requestType: application/vnd.courtscheduler.rotasl.process_rota_files+json
            name: courtscheduler.rotasl.process_rota_files
        ...
    body:
      application/vnd.courtscheduler.rotasl.process_rota_files+json:
    responses:
      202:
        description: Request Accepted
